"""
import_service.py
-----------------
High-performance file import — chunked + parallel via Redis worker pool.

Flow per file:
  1. POST /start  →  start_import_job()
       Creates enrichment_jobs record, fires asyncio.create_task(_stage_and_chunk())

  2. _stage_and_chunk()  [background, per file]
       a. Parse file (Python)
       b. COPY all rows → import_stage_{job_id}  (COPY protocol, ~50K rows/sec)
       c. Split staging into CHUNK_SIZE-row tables:
            import_chunk_{job_id}_0, import_chunk_{job_id}_1, ...
       d. RPUSH each chunk task → wb:import:chunks  (Redis)
       e. Drop main staging table
       f. Save unmapped columns → import_unmapped_data

  3. import_worker._worker() × 4  [BLPOP loop]
       Each worker: INSERT SELECT (xmax dedup) → update Redis progress
       Last chunk of a job → _finalise() writes counts to DB

Concurrency limits:
  - asyncpg pool: max 10 connections (shared across all features)
  - COPY_BATCH: 10K rows per COPY call (balances round-trips vs memory)
  - CHUNK_SIZE: 50K rows per Redis chunk task (4 workers × 50K = 200K in parallel)

Deduplication:
  - ON CONFLICT (id) DO UPDATE — existing leads updated in-place
  - xmax = 0  → new insert
  - xmax != 0 → duplicate updated
"""

from __future__ import annotations

import asyncio
import csv
import hashlib
import io
import re
import sys

# Raise CSV field size limit to the platform max (default 128 KB is too small)
try:
    csv.field_size_limit(sys.maxsize)
except OverflowError:
    csv.field_size_limit(2_147_483_647)  # 2 GB fallback for 32-bit platforms
import json
import logging
import math
import os
import uuid
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


def _normalize_linkedin_url(url: str) -> str:
    """
    Normalize a LinkedIn URL to the same canonical form used by the bulk
    enrichment API (_normalize_linkedin_url in lead_enrichment_brightdata_service).

    Rules (must stay in sync with the service):
      1. Strip whitespace + trailing slash
      2. Prepend https:// if no scheme
      3. Normalize country-specific subdomains (in., nl., uk., de., etc.) → www.
      4. Lowercase the path portion only (preserve domain casing)

    This ensures MD5(normalized_url) matches the lead ID generated by the
    bulk enrichment API for the same person.
    """
    if not url:
        return url
    url = url.strip().rstrip("/")
    if not url.startswith("http"):
        url = f"https://{url}"
    # country subdomain → www  (e.g. https://in.linkedin.com → https://www.linkedin.com)
    url = re.sub(r"https?://[a-z]{2}\.linkedin\.com", "https://www.linkedin.com", url)
    return url


CHUNK_SIZE  = 50_000    # rows per Redis chunk task
COPY_BATCH  = 10_000    # rows per COPY call — larger batches reduce round-trips to remote DB
REDIS_URL   = os.getenv("REDIS_URL", "redis://localhost:6379/0")
QUEUE_KEY   = "wb:import:chunks"
JOB_KEY_TPL = "wb:import:job:{job_id}"

# ─────────────────────────────────────────────────────────────────────────────
# Apollo + HubSpot + LinkedIn + Salesforce column → DB field auto-map
# ─────────────────────────────────────────────────────────────────────────────
_NORM_TO_FIELD: dict[str, str] = {
    "personname": "name", "fullname": "name", "name": "name",
    "firstname": "first_name", "personfirstname": "first_name",
    "personfirstnameunanalyzed": "first_name",
    "lastname": "last_name", "personlastname": "last_name",
    "personlastnameunanalyzed": "last_name",
    "personemail": "work_email", "email": "work_email",
    "emailaddress": "work_email", "workemail": "work_email",
    "personalemail": "personal_email",
    "personphone": "direct_phone", "phonenumber": "direct_phone",
    "phone": "direct_phone", "directphone": "direct_phone",
    "mobilephone": "direct_phone", "mobile": "direct_phone",
    "personlinkedinurl": "linkedin_url", "linkedinurl": "linkedin_url",
    "linkedin": "linkedin_url", "profileurl": "linkedin_url",
    "linkedinprofileurl": "linkedin_url",
    "persontwitter": "twitter", "twitterurl": "twitter", "twitter": "twitter",
    "persontitle": "title", "title": "title", "jobtitle": "title",
    "position": "title", "role": "title",
    "personseniority": "seniority_level", "seniority": "seniority_level",
    "senioritylevel": "seniority_level", "level": "seniority_level",
    "personfunctions": "department", "department": "department",
    "function": "department", "division": "department",
    "personlocationcity": "city", "city": "city",
    "personlocationcountry": "country", "country": "country",
    "location": "city", "personlocationstate": "city",
    "sanitizedorganizationnameunanalyzed": "company",
    "organizationname": "company", "company": "company",
    "companyname": "company", "accountname": "company",
    "organization": "company", "employer": "company",
    "organizationwebsite": "company_website", "companywebsite": "company_website",
    "website": "company_website", "domain": "company_website",
    "organizationindustry": "industry", "industry": "industry", "sector": "industry",
    "organizationnumemployeesrangemin": "employee_count",
    "employeecount": "employee_count", "employees": "employee_count",
    "companysizemin": "employee_count",
    "hqlocation": "hq_location", "headquarterslocation": "hq_location", "hq": "hq_location",
    "foundedyear": "founded_year", "founded": "founded_year", "yearfounded": "founded_year",
    "fundingstage": "funding_stage", "fundingtype": "funding_stage",
    "latestfundingtype": "funding_stage",
    "totalfunding": "total_funding", "totalfundingamount": "total_funding",
    "annualrevenue": "annual_revenue", "revenue": "annual_revenue",
    "personemailstatuscd": "email_source", "emailstatus": "email_source",
    "personextrapolatedemailconfidence": "email_confidence",
    "emailconfidence": "email_confidence",
    "personnumlinkedinconnections": "connections",
    "linkedinconnections": "connections", "connections": "connections",
    "followers": "followers",
    "about": "about", "summary": "about", "bio": "about",
    "headline": "about", "description": "about",
    "tags": "tags", "keywords": "tags", "labels": "tags",
    "timezone": "timezone", "timezone_cd": "timezone",
}

IMPORTABLE_FIELDS = sorted({
    "linkedin_url", "name", "first_name", "last_name",
    "work_email", "personal_email", "direct_phone", "twitter",
    "title", "seniority_level", "department",
    "city", "country", "timezone",
    "company", "industry", "company_website",
    "employee_count", "hq_location", "founded_year",
    "funding_stage", "total_funding", "annual_revenue",
    "tags", "about", "email_source", "email_confidence",
    "connections", "followers",
})

_STAGING_COLS = [
    "_row_uuid",
    "linkedin_url", "name", "first_name", "last_name",
    "work_email", "personal_email", "direct_phone", "twitter",
    "title", "seniority_level", "department",
    "city", "country", "timezone",
    "company", "industry", "company_website",
    "employee_count", "hq_location", "founded_year",
    "funding_stage", "total_funding", "annual_revenue",
    "tags", "about", "email_source", "email_confidence",
    "connections", "followers",
]
_DATA_COLS = _STAGING_COLS[1:]

_STAGING_DDL = """
    _row_uuid        TEXT,
    linkedin_url     TEXT,
    name             TEXT,
    first_name       TEXT,
    last_name        TEXT,
    work_email       TEXT,
    personal_email   TEXT,
    direct_phone     TEXT,
    twitter          TEXT,
    title            TEXT,
    seniority_level  TEXT,
    department       TEXT,
    city             TEXT,
    country          TEXT,
    timezone         TEXT,
    company          TEXT,
    industry         TEXT,
    company_website  TEXT,
    employee_count   TEXT,
    hq_location      TEXT,
    founded_year     TEXT,
    funding_stage    TEXT,
    total_funding    TEXT,
    annual_revenue   TEXT,
    tags             TEXT,
    about            TEXT,
    email_source     TEXT,
    email_confidence TEXT,
    connections      TEXT,
    followers        TEXT
"""


# ─────────────────────────────────────────────────────────────────────────────
# File helpers
# ─────────────────────────────────────────────────────────────────────────────

def _file_hash(data: bytes) -> str:
    return hashlib.md5(data).hexdigest()


def _file_hash_fast(data: bytes) -> str:
    """Fast fingerprint: MD5 of first 64 KB + file size.
    Sufficient for duplicate detection; avoids hashing 500 MB files."""
    h = hashlib.md5(data[:65536])
    h.update(str(len(data)).encode())
    return h.hexdigest()


def _norm(s: str) -> str:
    return s.lower().replace(" ", "").replace("_", "").replace("-", "").replace(".", "")


# ── Full-read helpers (used by _load_file for actual import) ──────────────────

def _read_csv_tsv(data: bytes, delim: str) -> tuple[list[str], list[list[str]]]:
    text = data.decode("utf-8-sig", errors="replace")
    reader = csv.reader(io.StringIO(text), delimiter=delim)
    rows = list(reader)
    if not rows:
        return [], []
    return rows[0], rows[1:]


def _read_excel(data: bytes, filename: str) -> tuple[list[str], list[list[str]]]:
    ext = filename.rsplit(".", 1)[-1].lower()
    if ext == "xls":
        import xlrd
        wb = xlrd.open_workbook(file_contents=data)
        ws = wb.sheet_by_index(0)
        if ws.nrows == 0:
            return [], []
        return (
            [str(ws.cell_value(0, c)) for c in range(ws.ncols)],
            [[str(ws.cell_value(r, c)) for c in range(ws.ncols)] for r in range(1, ws.nrows)],
        )
    else:
        import openpyxl
        wb = openpyxl.load_workbook(io.BytesIO(data), read_only=True, data_only=True)
        ws = wb.active
        all_rows = list(ws.iter_rows(values_only=True))
        wb.close()
        if not all_rows:
            return [], []
        return (
            [str(c) if c is not None else "" for c in all_rows[0]],
            [[str(c) if c is not None else "" for c in r] for r in all_rows[1:]],
        )


def _load_file(data: bytes, filename: str) -> tuple[str, list[str], list[list[str]]]:
    ext = filename.rsplit(".", 1)[-1].lower()
    if ext == "csv":
        return "csv", *_read_csv_tsv(data, ",")
    elif ext == "tsv":
        return "tsv", *_read_csv_tsv(data, "\t")
    elif ext in ("xls", "xlsx"):
        return ext, *_read_excel(data, filename)
    raise ValueError(f"Unsupported file type: .{ext}")


# ── Preview-only fast readers (stop after PREVIEW_ROWS, use metadata for count) ─

PREVIEW_ROWS = 10


def _preview_csv_tsv(data: bytes, delim: str) -> tuple[list[str], list[list[str]], int]:
    """
    Fast preview for CSV/TSV:
    - Row count from raw byte newline scan (C-speed, no full decode)
    - Headers + sample from first 64 KB only (no full file parse)
    """
    # Fast row count: count newlines in raw bytes minus the header line
    total = max(0, data.count(b'\n') - 1)

    # Parse headers + sample from first 64 KB only
    chunk_bytes = data[:65536]
    # Trim to the last complete line so csv.reader sees no truncated row
    last_nl = chunk_bytes.rfind(b'\n')
    if last_nl > 0:
        chunk_bytes = chunk_bytes[:last_nl]
    chunk = chunk_bytes.decode("utf-8-sig", errors="replace")

    reader = csv.reader(io.StringIO(chunk), delimiter=delim)
    try:
        headers = next(reader)
    except StopIteration:
        return [], [], total
    import itertools
    sample = list(itertools.islice(reader, PREVIEW_ROWS))
    return headers, sample, total


def _preview_xlsx(data: bytes) -> tuple[list[str], list[list[str]], int]:
    """Read headers + first 10 rows; use ws.max_row for total (no full iteration)."""
    import openpyxl
    wb = openpyxl.load_workbook(io.BytesIO(data), read_only=True, data_only=True)
    ws = wb.active
    # max_row is stored in sheet metadata — available without iterating all rows
    total = max(0, (ws.max_row or 1) - 1)
    rows_iter = ws.iter_rows(values_only=True)
    try:
        headers = [str(c) if c is not None else "" for c in next(rows_iter)]
    except StopIteration:
        wb.close()
        return [], [], 0
    sample: list[list[str]] = []
    for i, row in enumerate(rows_iter):
        if i >= PREVIEW_ROWS:
            break
        sample.append([str(c) if c is not None else "" for c in row])
    wb.close()
    return headers, sample, total


def _preview_xls(data: bytes) -> tuple[list[str], list[list[str]], int]:
    """Read headers + first 10 rows; use ws.nrows for total."""
    import xlrd
    wb = xlrd.open_workbook(file_contents=data)
    ws = wb.sheet_by_index(0)
    if ws.nrows == 0:
        return [], [], 0
    headers = [str(ws.cell_value(0, c)) for c in range(ws.ncols)]
    sample = [
        [str(ws.cell_value(r, c)) for c in range(ws.ncols)]
        for r in range(1, min(1 + PREVIEW_ROWS, ws.nrows))
    ]
    return headers, sample, ws.nrows - 1


# ─────────────────────────────────────────────────────────────────────────────
# Auto-mapping + preview
# ─────────────────────────────────────────────────────────────────────────────

def auto_suggest_mapping(columns: list[str]) -> dict[str, str]:
    return {col: _NORM_TO_FIELD.get(_norm(col), "") for col in columns}


def parse_preview(file_bytes: bytes, filename: str) -> dict:
    """
    Fast preview — reads only headers + first 10 rows.
    Does NOT load the entire file. Uses metadata for row count.
    """
    ext = filename.rsplit(".", 1)[-1].lower()
    if ext == "csv":
        file_type = "csv"
        headers, sample, total = _preview_csv_tsv(file_bytes, ",")
    elif ext == "tsv":
        file_type = "tsv"
        headers, sample, total = _preview_csv_tsv(file_bytes, "\t")
    elif ext == "xlsx":
        file_type = "xlsx"
        headers, sample, total = _preview_xlsx(file_bytes)
    elif ext == "xls":
        file_type = "xls"
        headers, sample, total = _preview_xls(file_bytes)
    else:
        raise ValueError(f"Unsupported file type: .{ext}")

    return {
        "file_type":         file_type,
        "columns":           headers,
        "rows":              [dict(zip(headers, row)) for row in sample],
        "total_rows":        total,
        "suggested_mapping": auto_suggest_mapping(headers),
        "file_hash":         _file_hash_fast(file_bytes),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Schema bootstrap
# ─────────────────────────────────────────────────────────────────────────────

async def _ensure_schema() -> None:
    from db import get_pool
    async with get_pool().acquire() as conn:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS import_unmapped_data (
                id          TEXT PRIMARY KEY,
                lead_id     TEXT NOT NULL,
                org_id      TEXT NOT NULL DEFAULT 'default',
                source_file TEXT,
                job_id      TEXT,
                raw_data    TEXT NOT NULL,
                created_at  TEXT
            )
        """)
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_unmapped_lead ON import_unmapped_data(lead_id)")
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_unmapped_org  ON import_unmapped_data(org_id, created_at DESC)")

        for ddl in [
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS filename TEXT",
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS file_hash TEXT",
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS folder_id TEXT",
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS skipped INTEGER DEFAULT 0",
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS new_count INTEGER DEFAULT 0",
            "ALTER TABLE enrichment_jobs ADD COLUMN IF NOT EXISTS updated_count INTEGER DEFAULT 0",
        ]:
            await conn.execute(ddl)

        await conn.execute("CREATE INDEX IF NOT EXISTS idx_jobs_filename  ON enrichment_jobs(organization_id, filename)")
        await conn.execute("CREATE INDEX IF NOT EXISTS idx_jobs_folder_id ON enrichment_jobs(folder_id)")


# ─────────────────────────────────────────────────────────────────────────────
# Row builders
# ─────────────────────────────────────────────────────────────────────────────

def _build_col_maps(
    headers: list[str],
    mapping: dict[str, str],
) -> tuple[dict[int, str], dict[int, str]]:
    col_to_field:   dict[int, str] = {}
    col_to_unmapped: dict[int, str] = {}
    for i, h in enumerate(headers):
        field = mapping.get(h, "")
        if field and field in IMPORTABLE_FIELDS:
            col_to_field[i] = field
        elif h.strip():
            col_to_unmapped[i] = h
    return col_to_field, col_to_unmapped


def _build_row(
    row: list[str],
    col_to_field: dict[int, str],
    col_to_unmapped: dict[int, str],
) -> tuple[dict[str, str], dict[str, str]]:
    mapped:   dict[str, str] = {}
    unmapped: dict[str, str] = {}
    for idx, field in col_to_field.items():
        val = row[idx].strip() if idx < len(row) else ""
        if val:
            mapped[field] = val
    for idx, col_name in col_to_unmapped.items():
        val = row[idx].strip() if idx < len(row) else ""
        if val:
            unmapped[col_name] = val
    return mapped, unmapped


def _to_staging_tuple(record: dict[str, str], row_uuid: str) -> tuple:
    return (row_uuid,) + tuple(record.get(col) or None for col in _DATA_COLS)


# ─────────────────────────────────────────────────────────────────────────────
# Redis helper
# ─────────────────────────────────────────────────────────────────────────────

async def _get_redis() -> Any:
    import redis.asyncio as aioredis
    return aioredis.from_url(REDIS_URL, decode_responses=True)


# ─────────────────────────────────────────────────────────────────────────────
# DB update helper
# ─────────────────────────────────────────────────────────────────────────────

async def _upd_job(job_id: str, **kw: Any) -> None:
    from db import get_pool
    keys = list(kw.keys())
    sets = ", ".join(f"{k}=${i+1}" for i, k in enumerate(keys))
    args = [kw[k] for k in keys] + [job_id]
    async with get_pool().acquire() as conn:
        await conn.execute(f"UPDATE enrichment_jobs SET {sets} WHERE id=${len(args)}", *args)


# ─────────────────────────────────────────────────────────────────────────────
# Background worker: parse → COPY → split chunks → push to Redis
# ─────────────────────────────────────────────────────────────────────────────

async def _stage_and_chunk(
    file_bytes: bytes,
    filename:   str,
    file_hash:  str,
    mapping:    dict[str, str],
    org_id:     str,
    job_id:     str,
) -> None:
    from db import get_pool

    pool = get_pool()
    now  = datetime.now(timezone.utc).isoformat()
    staging_base = f"import_stage_{job_id.replace('-', '_')}"

    try:
        await _ensure_schema()
        await _upd_job(job_id, status="running", updated_at=now)

        # ── 1. Parse file ────────────────────────────────────────────────────
        _, headers, rows = _load_file(file_bytes, filename)
        total = len(rows)
        await _upd_job(job_id, total_urls=total, updated_at=now)
        logger.info("[import %s] parsed %d rows from '%s'", job_id[:8], total, filename)

        col_to_field, col_to_unmapped = _build_col_maps(headers, mapping)
        if not col_to_field:
            await _upd_job(job_id, status="failed", error="No valid column mapping provided", updated_at=now)
            return

        # ── 2. Build staging tuples ──────────────────────────────────────────
        staging_tuples: list[tuple] = []
        unmapped_tuples: list[tuple] = []
        skipped = 0

        for row in rows:
            mapped, unmapped = _build_row(row, col_to_field, col_to_unmapped)
            # Normalize LinkedIn URL so MD5-based lead ID matches the bulk enrichment API
            if mapped.get("linkedin_url"):
                mapped["linkedin_url"] = _normalize_linkedin_url(mapped["linkedin_url"])
            has_key = mapped.get("linkedin_url") or mapped.get("work_email") or mapped.get("personal_email")
            if not has_key:
                skipped += 1
                continue

            row_uuid = str(uuid.uuid4())
            lead_id  = mapped.get("linkedin_url") or row_uuid
            staging_tuples.append(_to_staging_tuple(mapped, row_uuid))

            if unmapped:
                unmapped_tuples.append((
                    str(uuid.uuid4()), lead_id, org_id, filename, job_id,
                    json.dumps(unmapped, ensure_ascii=False), now,
                ))

        if not staging_tuples:
            await _upd_job(job_id, status="completed", processed=0, skipped=skipped,
                           error=f"All {skipped} rows skipped — no linkedin_url/email",
                           updated_at=now)
            return

        n_valid = len(staging_tuples)
        logger.info("[import %s] %d valid rows, %d skipped, splitting into %d chunks of %d",
                    job_id[:8], n_valid, skipped, math.ceil(n_valid / CHUNK_SIZE), CHUNK_SIZE)

        # ── 3. COPY all rows → main staging table ────────────────────────────
        async with pool.acquire() as conn:
            await conn.execute("SET synchronous_commit = OFF")
            await conn.execute(f"DROP TABLE IF EXISTS {staging_base}")
            await conn.execute(f"CREATE UNLOGGED TABLE {staging_base} ({_STAGING_DDL})")

            copied = 0
            for i in range(0, n_valid, COPY_BATCH):
                batch = staging_tuples[i: i + COPY_BATCH]
                await conn.copy_records_to_table(staging_base, records=batch, columns=_STAGING_COLS)
                copied += len(batch)
                # 0–40 % progress during COPY phase
                await _upd_job(job_id, processed=int(copied / n_valid * total * 0.4), updated_at=now)

        logger.info("[import %s] COPY done (%d rows) — splitting into chunks", job_id[:8], n_valid)

        # ── 4. Split main staging → chunk staging tables + push to Redis ─────
        n_chunks = max(1, math.ceil(n_valid / CHUNK_SIZE))
        r = await _get_redis()

        for chunk_idx in range(n_chunks):
            chunk_staging = f"import_chunk_{job_id.replace('-', '_')}_{chunk_idx}"
            offset = chunk_idx * CHUNK_SIZE
            async with pool.acquire() as conn:
                await conn.execute(f"DROP TABLE IF EXISTS {chunk_staging}")
                await conn.execute(
                    f"CREATE UNLOGGED TABLE {chunk_staging} AS "
                    f"SELECT * FROM {staging_base} LIMIT {CHUNK_SIZE} OFFSET {offset}"
                )

            await r.rpush(QUEUE_KEY, json.dumps({
                "job_id":       job_id,
                "chunk_idx":    chunk_idx,
                "total_chunks": n_chunks,
                "staging":      chunk_staging,
                "org_id":       org_id,
                "filename":     filename,
                "now":          now,
            }))

        # Initialise Redis job progress tracker
        await r.hset(JOB_KEY_TPL.format(job_id=job_id), mapping={
            "done":          0,
            "total_chunks":  n_chunks,
            "total":         total,
            "new_count":     0,
            "updated_count": 0,
            "processed":     0,
            "skipped":       skipped,
        })
        await r.aclose()

        # Drop main staging (chunk tables remain for workers to consume)
        async with pool.acquire() as conn:
            await conn.execute(f"DROP TABLE IF EXISTS {staging_base}")

        logger.info("[import %s] %d chunk tasks pushed to Redis queue", job_id[:8], n_chunks)

        # ── 5. Save unmapped data ────────────────────────────────────────────
        if unmapped_tuples:
            async with pool.acquire() as conn:
                await conn.copy_records_to_table(
                    "import_unmapped_data",
                    records=unmapped_tuples,
                    columns=["id", "lead_id", "org_id", "source_file", "job_id", "raw_data", "created_at"],
                )
            logger.info("[import %s] saved %d unmapped rows", job_id[:8], len(unmapped_tuples))

    except Exception as exc:
        err_str = str(exc)
        if "No space left" in err_str or "FileFallocate" in err_str or "ENOSPC" in err_str:
            err_str = (
                "Database disk full — no space left on device. "
                "Free up space or upgrade your database plan, then retry."
            )
        elif "field larger than field limit" in err_str:
            err_str = f"CSV field too large — a cell in your file exceeds the maximum allowed size. {err_str}"
        logger.exception("[import %s] stage_and_chunk failed: %s", job_id[:8], exc)
        try:
            async with pool.acquire() as conn:
                await conn.execute(f"DROP TABLE IF EXISTS {staging_base}")
        except Exception:
            pass
        await _upd_job(job_id, status="failed", error=err_str[:500], updated_at=now)


# ─────────────────────────────────────────────────────────────────────────────
# Public entry points
# ─────────────────────────────────────────────────────────────────────────────

async def start_import_job(
    file_bytes: bytes,
    filename:   str,
    mapping:    dict[str, str],
    org_id:     str,
    folder_id:  str | None = None,
) -> str:
    from db import get_pool

    job_id = str(uuid.uuid4())
    fhash  = _file_hash(file_bytes)
    now    = datetime.now(timezone.utc).isoformat()

    async with get_pool().acquire() as conn:
        await conn.execute(
            """
            INSERT INTO enrichment_jobs
                (id, organization_id, status, total_urls, processed, failed,
                 filename, file_hash, folder_id, skipped, new_count, updated_count,
                 created_at, updated_at)
            VALUES ($1, $2, 'pending', 0, 0, 0, $3, $4, $5, 0, 0, 0, $6, $6)
            """,
            job_id, org_id, filename, fhash, folder_id, now,
        )

    asyncio.create_task(
        _stage_and_chunk(file_bytes, filename, fhash, mapping, org_id, job_id),
        name=f"import-{job_id[:8]}",
    )
    return job_id


# ─────────────────────────────────────────────────────────────────────────────
# Query helpers (used by routes)
# ─────────────────────────────────────────────────────────────────────────────

async def get_import_history(org_id: str, page: int = 1, limit: int = 30) -> dict:
    from db import get_pool
    offset = (page - 1) * limit
    async with get_pool().acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, filename, file_hash, folder_id, status,
                   total_urls AS total, processed, new_count, updated_count, skipped, failed,
                   error, created_at, updated_at
            FROM enrichment_jobs
            WHERE organization_id = $1 AND filename IS NOT NULL
            ORDER BY created_at DESC
            LIMIT $2 OFFSET $3
            """,
            org_id, limit, offset,
        )
        total = await conn.fetchval(
            "SELECT COUNT(*) FROM enrichment_jobs WHERE organization_id=$1 AND filename IS NOT NULL",
            org_id,
        )
    return {"history": [dict(r) for r in rows], "total": total, "page": page, "limit": limit}


async def get_imported_filenames(org_id: str) -> list[str]:
    from db import get_pool
    async with get_pool().acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT DISTINCT filename FROM enrichment_jobs
            WHERE organization_id=$1 AND filename IS NOT NULL AND status='completed'
            ORDER BY filename
            """,
            org_id,
        )
    return [r["filename"] for r in rows]


async def get_folder_status(folder_id: str, org_id: str) -> dict:
    from db import get_pool
    async with get_pool().acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, filename, status,
                   total_urls AS total, processed, new_count, updated_count, skipped, failed, error,
                   created_at, updated_at
            FROM enrichment_jobs
            WHERE folder_id=$1 AND organization_id=$2
            ORDER BY created_at ASC
            """,
            folder_id, org_id,
        )

    jobs = []
    for r in rows:
        d   = dict(r)
        tot = int(d["total"] or 0)
        prc = int(d["processed"] or 0)
        d["pct"] = round(prc / tot * 100) if tot else 0
        jobs.append(d)

    total_files = len(jobs)
    completed   = sum(1 for j in jobs if j["status"] == "completed")
    failed      = sum(1 for j in jobs if j["status"] == "failed")
    running     = sum(1 for j in jobs if j["status"] in ("running", "pending"))

    return {
        "folder_id":    folder_id,
        "total_files":  total_files,
        "completed":    completed,
        "failed":       failed,
        "running":      running,
        "done":         (completed + failed == total_files) and total_files > 0,
        "total_new":    sum(j.get("new_count",     0) or 0 for j in jobs),
        "total_updated":sum(j.get("updated_count", 0) or 0 for j in jobs),
        "total_skipped":sum(j.get("skipped",       0) or 0 for j in jobs),
        "jobs":         jobs,
    }
